config/routes.rb
Demo::Application.routes.draw do
 	resource :demo
	resources :categories 
        resource :questions
	resource :answers
	resources :users do 
	  member do
             get :following, :followers
          end
        end
        resources :microposts
        resources :profiles
	resources :sessions
	
    

    
      
 match '/contact', :to => 'pages#contact'
    match '/about',   :to => 'pages#about'
    match '/help',    :to => 'pages#help'
    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'

    match 'sessions/:id/shownewuser',  :to => 'sessions#shownewuser' , :as => :shownewuser
    match 'sessions/:id/signedin',  :to => 'sessions#signedin' , :as => :signedin
    match 'profiles/setuserprofile',  :to => 'profiles#setuserprofile' , :as => :setuserprofile
    match 'sessions/:id/showsurvey', :to => 'sessions#showsurvey', :as => :showsurvey
    match 'sessions/:id/expressyourself', :to => 'sessions#expressyourself', :as => :expressyourself
    match 'sessions/:id/discuss', :to => 'sessions#discuss', :as => :discuss
    match 'sessions/:id/updateanswers', :to => 'sessions#updateanswers', :as => :updateanswers
    match 'sessions/:id/updateProfile', :to => 'sessions#updateProfile', :as => :updateProfile
    
    match '/signout', :to => 'sessions#destroy'
    root :to => 'sessions#signedin'
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
           @logged_in = false
           @cat = Category.all
           layout "prefrontpage"

 def index
          
 end
 def show
 	 
 end 	 
  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end  
end

app/views/demos/_UserLoggedOn.html.erb
<div class="just_for_a_border">
<div id="nav" >
<div class="left">
	<div class="right">
	   <ul class="tabs" id="bill_tab_select">
	     <% @cat.each do |tab| %>
		<li id='<%= tab[:id] %>' >
		<%= link_to "<span>#{tab[:title]}</span>" %>
		</li>
	     <% end %>
	  </ul>
       </div>
</div>
</div>
<div id ="questionlist">
<% @cat.each do |tab| 
		@id = tab[:id]
		@title = tab[:title] 
<ul class="medium_question_list" id ="questions_selected" >
 <div id='<%@id%>' style='display: none;' >
      <span><span id="popular_ul_title">@title</span>
</span>
<% end %>
</div>
</div><!-- just for a border -->

app/views/demos/_formlogin.html.erb
 <button>
 <%= link_to "Skip Intro", signin_path %>   
</button>

app/views/demos/_loggedin.html.erb
   <div heading class="group">
  </div>

app/views/demos/_questions.html.erb
 <table>
 <%@questions.each do |qs| %>
 <tr>
   <td> <%= qs[:question_id] %> </td>
   <td> <%= qs[:question] %> </td>
</tr>
<% end %>
</table>

app/views/demos/about.html.erb
<h1>About Us</h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/demos/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/demos/index.html.erb
<div id="content" class="clearfix">
 
 
 <%= render :partial => 'layouts/user_nav' %>

  <div class="inner">
    <div class="top_area">          
	<%if @signed_in == 'yes' then %>
	<%= render :partial => 'UserLoggedOn' %>
       <% else %>
  	  <h1>Sample App</h1>
	  <p>
	  This is the landingpage to sign up/a> sample application.
	  </p>
	  <%= link_to "Voter", signup_path, :class => "signup_button_voter round" %>
         <%= link_to "SignIn", signin_path %> Sign In  	  
	  <%= link_to "Politicians", signup_path, :class => "signup_button_politician round" %>
	<% end %>
	 <div id="find">
             <p>Where voters and politicians can discuss and learn about the issues for free with no advertising dollars getting in the way <br />Subscribe to RSS feeds to stay in touch with their latest votes. </p>
         </div>
    </div><!-- top_area -->
  </div><!-- inner -->
</div> <!-- content --> 

app/views/demos/show.html.erb
<div id="content" class="clearfix">
 
 
 <%= render :partial => 'layouts/user_nav' %>

  <div class="inner">
    <div class="top_area">          
	
	  <%= link_to "Voter", signup_path, :class => "signup_button_voter round" %>
          	  
	  <%= link_to "Politicians", signup_path, :class => "signup_button_politician round" %>
	 <div id="find">
             <p>Where voters and politicians can discuss and learn about the issues for free with no advertising dollars getting in the way <br />Subscribe to RSS feeds to stay in touch with their latest votes. </p>
         </div>
    </div><!-- top_area -->
  </div><!-- inner -->
</div> <!-- content --> 