config/routes.rb
Demo::Application.routes.draw do
 	resource :demo
	resources :categories 
        resource :questions
	resource :answers
	resources :users do 
	  member do
             get :following, :followers
          end
        end
        resources :microposts
        resources :profiles
	resources :sessions
	
    

    
      
 match '/contact', :to => 'pages#contact'
    match '/about',   :to => 'pages#about'
    match '/help',    :to => 'pages#help'
    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'

    match 'sessions/:id/shownewuser',  :to => 'sessions#shownewuser' , :as => :shownewuser
    match 'sessions/:id/signedin',  :to => 'sessions#signedin' , :as => :signedin
    match 'profiles/setuserprofile',  :to => 'profiles#setuserprofile' , :as => :setuserprofile
    match 'sessions/:id/showsurvey', :to => 'sessions#showsurvey', :as => :showsurvey
    match 'sessions/:id/expressyourself', :to => 'sessions#expressyourself', :as => :expressyourself
    match 'sessions/:id/discuss', :to => 'sessions#discuss', :as => :discuss
    match 'sessions/:id/updateanswers', :to => 'sessions#updateanswers', :as => :updateanswers
    match 'sessions/:id/updateProfile', :to => 'sessions#updateProfile', :as => :updateProfile
    
    match '/signout', :to => 'sessions#destroy'
    root :to => 'sessions#signedin'
end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :profiles_attributes
  has_one :profiles
  
  has_many :microposts,    :dependent => :destroy
  has_many :relationships, :dependent => :destroy,
                           :foreign_key => "follower_id"
  has_many :reverse_relationships, :dependent => :destroy,
                                   :foreign_key => "followed_id",
                                   :class_name => "Relationship"
  has_many :following, :through => :relationships, :source => :followed
  has_many :followers, :through => :reverse_relationships,
                       :source  => :follower
                       
  accepts_nested_attributes_for :profiles
  
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def feed
    Micropost.from_users_followed_by(self)
  end
  
  def following?(followed)
    relationships.find_by_followed_id(followed)
  end
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end
  
  class << self
    def authenticate(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
    
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end
  
  private
  
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
  
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate,
                :only => [:index, :edit, :update, :destroy,
                :followers, :following, :reps]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  layout "frontpage"
  respond_to :json
  
  def index
    @users = User.paginate(:page => params[:page])
    @title = "All users"
  end
  
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @title = @user.name
  end
  
  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(:page => params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    render 'show_follow'
  end

  def new
    @user  = User.new
    current_user = @user
    @title = "Sign up"
  end
  
  def create
    @user = User.new
    @user.email = params[:email]
    @user.password_digest = params[:password]
    @user.save
    current_user = @user
    @profile = Profile.new
    @profile.id = @user.id

     if @profile.save
 	    redirect_to shownewuser_path :id => @user.id
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def edit
    @title = "Edit user"  
  end
  
  def update
   if @user.update_attributes(params[:user])
      redirect_to @user, :flash => { :success => "Profile updated." }
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, :flash => { :success => "User destroyed." }
  end
    
  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      @user = User.find(params[:id])
      redirect_to(root_path) if !current_user.admin? || current_user?(@user)
    end
end

app/views/users/_form.html.erb
 <%= form_tag  users_path  do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password , params[:password]%>
  </div>
  <div class="field">
    <%= label_tag :password_confirmation %>
    <%= password_field_tag :password_confirmation, params[:password_confirmation] %>
  </div>
   <div class="actions">
   <%= submit_tag "Submit" %>
   </div>
 <% end %>  
  

app/views/users/_formlogin.html.erb
 <button>
 <%= link_to "Skip Intro", signin_path %>   
</button>

app/views/users/edit.html.erb
<div id="content" class="clearfix">
 <%= render :partial => 'layouts/user_nav' %>
 

  <div class="inner">
    <div class="top_area">          
<h1>Editing user</h1>

<%= render :partial =>'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.type %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div id="content" class="clearfix">
 
<div class="inner">
<div class="top_area">

 <h1>New user</h1>

<%= render :partial => 'form' %>

<%= link_to 'Back', users_path %>
  </div><!-- top_area -->
  </div><!-- inner -->
</div> <!-- content --> 

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @user.id %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Type:</b>
  <%= @user.type %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>