config/routes.rb
Demo::Application.routes.draw do
 	resource :demo
	resources :categories 
        resource :questions
	resource :answers
	resources :users do 
	  member do
             get :following, :followers
          end
        end
        resources :microposts
        resources :profiles
	resources :sessions
	
    

    
      
 match '/contact', :to => 'pages#contact'
    match '/about',   :to => 'pages#about'
    match '/help',    :to => 'pages#help'
    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'

    match 'sessions/:id/shownewuser',  :to => 'sessions#shownewuser' , :as => :shownewuser
    match 'sessions/:id/signedin',  :to => 'sessions#signedin' , :as => :signedin
    match 'profiles/setuserprofile',  :to => 'profiles#setuserprofile' , :as => :setuserprofile
    match 'sessions/:id/showsurvey', :to => 'sessions#showsurvey', :as => :showsurvey
    match 'sessions/:id/expressyourself', :to => 'sessions#expressyourself', :as => :expressyourself
    match 'sessions/:id/discuss', :to => 'sessions#discuss', :as => :discuss
    match 'sessions/:id/updateanswers', :to => 'sessions#updateanswers', :as => :updateanswers
    match 'sessions/:id/updateProfile', :to => 'sessions#updateProfile', :as => :updateProfile
    
    match '/signout', :to => 'sessions#destroy'
    root :to => 'sessions#signedin'
end

app/views/shared/_analytics_head.html.erb
<% if Rails.env.production? %>
   <%# chartbeat %>
   <script type="text/javascript">var _sf_startpt=(new Date()).getTime()</script>
<% end %>

app/views/shared/_commentary_options.html.erb
<% is_logged_in ||= false %>

<table class="combox" cellspacing="0" cellpadding="0">
	<tr>
		<td class="left"></td>
		<td class="mypnz_img">
			<%= image_tag "mypn-small.png", :alt => "Add to My Political Notebook" %>
		</td>
		<td class="mypnz_txt">
			<% if is_logged_in %>
							<% if PoliticalNotebook.find_or_create_from_user(current_user).already_contains? commentary %>
								<span>Saved</span>
							<% else %>
							<script type='text/javascript'>
							$j().ready(function() {
							  $j('#faceform_<%= commentary.id.to_s %>').jqm({ajax: '/users/<%= current_user.login %>/profile/political_notebook/notebook_links/faceform?id=<%= commentary.id %>&type=<%= commentary.class %>', trigger: 'a.trigger_<%= commentary.id.to_s %>'});
							});
							</script>     
							<span id="addmypn_<%= object.class %>_<%= object.id %>"><a href="#" class="trigger_<%= commentary.id.to_s %>" >Save</a></span>
							<div class="jqmWindow" id="faceform_<%= commentary.id.to_s %>">
							 <%= image_tag "indicator.gif", :class=>"noborder" %> 
							</div>
							<% end %>
			 <% else %>
				<span><%= link_to("Save to Notebook", :controller => "account", :action => "login") %></span>
			 <% end %>     
      
			        
		 </td>
	<td class="center"></td>
	<td class="ratez">
		<span id="comm_rate_<%= commentary.id.to_s%>">
		  <% if is_logged_in %>
			Rate
			<% else %>
		 <%= link_to("Rate", :controller => "account", :action => "login") %>
		<% end %>
	      <span id="comm_rate_ind_<%= commentary.id.to_s%>" style="display: none;">
	        <%= image_tag "indicator.gif", :class=>"noborder" %> 
	      </span>
	    </span>
	</td>
	<td class="ratez_form">
		<script type="text/javascript" language="javascript">
		$j(function(){ 
		 $j('.rate_<%= commentary.id.to_s %>').rating({
			callback: function(value, link){
				new Ajax.Updater('comm_rate_<%= commentary.id.to_s%>','/commentary/rate/<%= commentary.id %>?value=' + value, {asynchronous:true, evalScripts:true}); return false;
				}
		}); 
		});
		</script>
		<form id="rating_<%= commentary.id.to_s %>">  
			<% (1..10).each do |v| %>
		<input class="rate_<%= commentary.id.to_s %> {split:2}" type="radio" name="rate_<%= commentary.id.to_s %>" value="<%= v %>" <%= "disabled='disabled'" unless is_logged_in %><%= commentary.score == v ? "checked='checked'" : "" %> />
	  <% end %>
			</form>           
		 </td>
	</tr>
</table>

app/views/shared/_comments_list.html.haml
- if params[:comment_sort] == 'rating' 
  - comments = object.comments.paginate(:page => params[:comment_page], :include => [:user], :order => "comments.plus_score_count - comments.minus_score_count DESC" )
- elsif params[:comment_sort] == 'newest'
  - comments = object.comments.paginate(:page => params[:comment_page], :include => [:user], :order => "comments.created_at DESC" ) 
- else
  - comments = object.comments.paginate(:page => params[:comment_page], :include => [:user], :order => "comments.root_id ASC, comments.lft ASC" ) 
     
- if comments.size > 0
  - logged_in? ? myscores = current_user.comment_scores.find(:all) : myscores = Array.new
     
  - if comments.total_pages > 1
    %p.this_many
      = "Displaying #{comments.offset + 1}-#{(comments.offset + comments.per_page > comments.total_entries ) ? comments.total_entries : comments.offset + comments.per_page} of "
      %b= comments.total_entries 
      total comments.

  = render :partial => 'shared/comments_pagination', :locals => { :object => object, :comments => comments }

  - if (params[:comment_sort] == 'newest' || params[:comment_sort] == 'rating') # just display a flat list since nesting doesn't make sense when sort=newest, likewise for rating
    - comments.each do |node|
      = render :partial => 'shared/comments_comment', :locals => {:object => object, :comment => node, :myscores => myscores, :flat => true}
  - else
    = display_nested_set_rows(comments) { |node| render :partial => 'shared/comments_comment', :locals => {:object => object, :comment => node, :myscores => myscores} }

  = render :partial => 'shared/comments_pagination', :locals => { :object => object, :comments => comments }

  
= render :partial => 'shared/comments_add', :locals => {:parent_id => 0, :object => object, :master_container => master_container, :redirect => true }

- if @goto_comment
  :javascript
    = "window.onload = function() {" unless @ajax_comment
    new Effect.ScrollTo('com#{@goto_comment.id}', {offset: -10});
    new Effect.Highlight('com#{@goto_comment.id}', {duration: 2});
    = ";" unless @ajax_comment

app/views/shared/_custom_sidebar_item.html.erb
<% case item.sidebar.class_type
   when 'Bill' %>
    <%= link_to rb.title_full_common, :controller => 'bill', :action => 'show', :id => rb.ident %>
    (<%= rb.views(Settings.default_count_time) %> views)<br />
    <span class="date">
      Introduced on <%= Time.at(rb.introduced).strftime("%B %d, %Y") %><br /> 
      by the <%= rb.chamber.capitalize %>
    </span>
<% when 'Person' %>
    <p><%= link_to_person item.person %></p>
    <img src="/images/photos/<%= item.person.id -%>.jpeg" height="50" alt="person" /><br />
    (<%= item.views(Settings.default_count_time) %> views)
<% when 'Committee' %>
    <p><%= link_to_item item.committee, :proper_name, :show %> (<%= item.views(Settings.default_count_time) %> views)</p>
    <% unless item.committee.chair.nil? -%>
      <p>Chair: <%= link_to_person item.committee.chair %></p>
    <% end -%>
    <% unless item.committee.ranking_member.nil? -%>
      <p>Ranking Member: <%= link_to_person item.committee.ranking_member %></p>
    <% end -%>
<% when 'Subject' %>
    <p><%= link_to_item item.subject, :term, :show %> (<%= item.views(Settings.default_count_time) %> views)</p>
    <p>Bills: <%= item.subject.bills_count %>
<% end %>

<% if item.description %>
  <p class="sidebar_item_description"><%= item.description %></p>
<% end %>

app/views/shared/_email_form.html.erb
<script type="text/javascript" src="http://www.plaxo.com/css/m/js/util.js"></script>
<script type="text/javascript" src="http://www.plaxo.com/css/m/js/prototype.js"></script>
<script type="text/javascript" src="http://www.plaxo.com/css/m/js/basic.js"></script>
<script type="text/javascript" src="http://www.plaxo.com/css/m/js/abc_launcher.js"></script>
<script type="text/javascript"><!--
function onABCommComplete() {
  // OPTIONAL: do something here after the new data has been populated in your text area
}
//-->
</script>

<dt><label>Your Email:</label></dt>
<dd><%= text_field 'email', 'email', 'value' => @email_from %></dd>
<dt><label>Friends' Emails:<br />(one per line)<br /><a href="#" onclick="showPlaxoABChooser('email_dest_emails', '/plaxo.html'); return false"><img class='noborder' src="http://www.plaxo.com/images/abc/buttons/add_button.gif" alt="Add from my address book" /></a></label></dt>
<dd>
<%= text_area 'email', 'dest_emails', "cols" => 30, "rows" => 7 %>
</dd>
<dt><label>Personal Message:<br />(optional)</label></dt>
<dd>
<%= text_area 'email', 'message', "cols" => 30, "rows" => 4 %>
</dd>
<dt>&nbsp;</dt>
<dd><%= check_box('email', 'cc_me' ) %> Send me a copy</dd>
<%= show_simple_captcha(:image_style => 'all_black', :distortion => 'high') %>
<div style="padding-left: 220px; font-size: 15px;">
<%= submit_tag "Send >>" %>
</div>

app/views/shared/_error_messages.html.haml
- if target.errors.any?
  #errors
    %h3 There was an error with your submission!
    %ul  
      - target.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <table class="microposts" summary="Status feed">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
<% end %>

app/views/shared/_generic_search_field.html.erb
<form method="get" class="search_form">
<div>
		<%= field_text.html_safe %> <input name="q" id="search-field" type="text" size="30" value="<%= @q %>" />
  		<input type="image" src="<%= image_path 'search_submit.gif' %>" name="submit" id="search_submit" value="Search">

</div>

</form>

app/views/shared/_sort_comments.html.erb
<ul id="sort" class="sort_comments">
<h4>Sort By</h4>
    <li id="oldest" class="<%= (params[:comment_sort] == 'oldest' || params[:comment_sort].blank?) ? "active" : "" %>">
    	<%= link_to "<span>Oldest First</span>".html_safe, :comment_sort => 'oldest' %>
    </li>
		<li id="newest" class="<%= params[:comment_sort] == 'newest' ? "active" : "" %>">
			<%= link_to "<span>Newest First</span>".html_safe, :comment_sort => 'newest' %>
	 	</li>

		<li id="rating" class="<%= params[:comment_sort] == 'rating' ? "active" : "" %>">
			<%= link_to "<span>Highest Rated</span>".html_safe, :comment_sort => 'rating' %>
		</li>
</ul>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_stats_box.html.erb
<div id="stats">
  <% cache("page_views_#{stats_box.display_object_name}_#{stats_box.id}", :expires_in => 3.hours) do %>
    <!-- cached: page_views_<%= "#{stats_box.display_object_name}_#{stats_box.id}" %> // <%= Time.now %> -->
    <h3><%= stats_box.display_object_name %>'s Views</h3>
    <ul>
      <li><span class="time">Today:</span> <span class="count"><%= number_with_delimiter(stats_box.views(1.days)) %></span></li>
      <li class="even">
        <span class="time">Past Seven Days:</span> <span class="count"><%= number_with_delimiter(stats_box.views(7.days)) %></span>
      </li>
      <li><span class="time">All-Time:</span> <span class="count"><%= number_with_delimiter(stats_box.views) %></span></li>
    </ul>
    <!-- /page_views_<%= "#{stats_box.display_object_name}_#{stats_box.id}" %> -->
  <% end %>
	</div>

app/views/shared/_support_oppose_tables.html.erb
<% cache("#{stance}_items_#{object.display_object_name}_#{object.id}", :expires_in => 24.hours) do %>
  <!-- cached: tracked_items_<%= "#{object.display_object_name}_#{object.id}" %> // <%= Time.now %> -->
 <div class="user_also_wrap"> 
  <h2 class="clear">Users <b><%= stance %></b> <%= title %> 
     (<%= link_to tracking_suggestions[0], :controller => 'friends', :action => action, :id => (object.class.to_s == 'Subject' ? object.to_param : object.ident ) %>) <span>are also:</span>
  </h2>
  <table style="width:100%;">
    <tr>
      <% unless tracking_suggestions[1][:my_bills_supported_facet].blank? %><th style="width:380px;text-align:left;">Supporting Bill</th><% end %>
			<% unless tracking_suggestions[1][:my_approved_sens_facet].blank? %><th style="width:280px;text-align:left;">Supporting Senator</th><% end %>
      <% unless tracking_suggestions[1][:my_approved_reps_facet].blank? %><th style="width:280px;text-align:left;">Supporting Representative</th><% end %>
    </tr>
    <tr>
      <%  unless tracking_suggestions[1][:my_bills_supported_facet].blank? %>
      <td style="vertical-align:top;">
        <ul class="mini_bills_list">
        <% tracking_suggestions[1][:my_bills_supported_facet].each do |p| %>
          <li><%= link_to p[:object].typenumber, bill_path(p[:object]) %> <%= truncate_string(p[:object].title_short, 20) %>
            <%= link_to "<span>#{p[:trackers]}</span>".html_safe, :controller => 'friends', :action => 'supporting_bill', :id => p[:object].ident %></li>
        <% end %>
        </ul>
      </td>
      <% end %>  
		 <%  unless tracking_suggestions[1][:my_approved_sens_facet].blank? %>
      <td style="vertical-align:top;">
        <ul class="mini_sens_list">
        <% tracking_suggestions[1][:my_approved_sens_facet].each do |p| %>
          <li><%= link_to "#{p[:object].short_name} <i>[#{p[:object].party_and_state}]</i>".html_safe, person_url(p[:object].ident) %> 
            <%= link_to "<span>#{p[:trackers]}</span>".html_safe, :controller => 'friends', :action => 'supporting_person', :id => p[:object].ident %></li>
        <% end %>
        </ul>
      </td>
      <% end %>
      <%  unless tracking_suggestions[1][:my_approved_reps_facet].blank? %>
      <td style="vertical-align:top;">
        <ul class="mini_reps_list">
        <% tracking_suggestions[1][:my_approved_reps_facet].each do |p| %>
          <li><%= link_to "#{p[:object].short_name} <i>[#{p[:object].party_and_state}]</i>".html_safe, person_url(p[:object].ident) %> 
            <%= link_to "<span>#{p[:trackers]}</span>".html_safe, :controller => 'friends', :action => 'supporting_person', :id => p[:object].ident %></li>
        <% end %>
        </ul>
      </td>
      <% end %>
     
    </tr>
</table>
<br /><br />
<table style="width:100%;">
  <tr>
		<% unless tracking_suggestions[1][:my_bills_opposed_facet].blank? %><th style="width:380px;text-align:left;">Opposing Bill</th><% end %>
      
     <% unless tracking_suggestions[1][:my_disapproved_sens_facet].blank? %><th style="width:280px;text-align:left;">Opposing Senator</th><% end %>
      <% unless tracking_suggestions[1][:my_disapproved_reps_facet].blank? %><th style="width:280px;text-align:left;">Opposing Representative</th><% end %>
  </tr>
  <tr>
       <%  unless tracking_suggestions[1][:my_bills_opposed_facet].blank? %>
	      <td style="vertical-align:top;">
	        <ul class="mini_bills_list">
	        <% tracking_suggestions[1][:my_bills_opposed_facet].each do |p| %>
	          <li><%= link_to p[:object].typenumber, bill_path(p[:object]) %> <%= truncate_string(p[:object].title_short, 20) %>
	            <%= link_to "<span>#{p[:trackers]}</span>".html_safe, :controller => 'friends', :action => 'opposing_bill', :id => p[:object].ident %></li>
	        <% end %>
	        </ul>
	      </td>
	      <% end %>
      
      <%  unless tracking_suggestions[1][:my_disapproved_sens_facet].blank? %>
      <td style="vertical-align:top;">
        <ul class="mini_sens_list">
        <% tracking_suggestions[1][:my_disapproved_sens_facet].each do |p| %>
          <li><%= link_to "#{p[:object].short_name} <i>[#{p[:object].party_and_state}]</i>".html_safe, person_url(p[:object].ident) %> 
            <%= link_to "<span>#{p[:trackers]}</span>".html_safe, :controller => 'friends', :action => 'opposing_person', :id => p[:object].ident %></li>
        <% end %>
        </ul>
      </td>
      <% end %>
            
      <%  unless tracking_suggestions[1][:my_disapproved_reps_facet].blank? %>
      <td style="vertical-align:top;">
        <ul class="mini_reps_list">
        <% tracking_suggestions[1][:my_disapproved_reps_facet].each do |p| %>
          <li><%= link_to "#{p[:object].short_name} <i>[#{p[:object].party_and_state}]</i>".html_safe, person_url(p[:object].ident) %> 
            <%= link_to "<span>#{p[:trackers]}</span>".html_safe, :controller => 'friends', :action => 'opposing_person', :id => p[:object].ident %></li>
        <% end %>
        </ul>
      </td>
      <% end %>
      
    </tr>
  </table>
  </div>
<% end %>

app/views/shared/_timeframe_select.html.erb
<div id="timeframe">


<% @sort ||= "" %>
<% if (@congress.nil? or (@congress == Settings.default_congress)) %>
  <ul id="timeframe_select" class="<%= @sort %>">
  	<li class="<%= @days == 7.days ? "selected" : "" %>">
  		<%= link_to "7 days", :days => 7, :sort => @sort %>
  	</li>
  	<li class="<%= @days == 14.days ? "selected" : "" %>">
  		<%= link_to "14 days", :days => 14, :sort => @sort %>	
  	</li>
  	<li class="<%= @days == 30.days ? "selected" : "" %>">
  		<%= link_to "30 days", :days => 30, :sort => @sort %>
  	</li>
  	<li class="<%= @days == 365.days ? "selected" : "" %>">
  		<%= link_to "Past Year", :days => 365, :sort => @sort %>
  	</li>
  </ul>
<% end %>
<!-- // timeframe-->
</div>

app/views/shared/_track_link.html.erb
<% button = "track_small" unless button %>	
<span id="trackli<%=h object.id %>">
  <% if logged_in? == false or object.bookmarks.find_by_user_id(current_user.id) == nil %>
    <% if logged_in? %>
      <%= link_to_remote "<span>Track #{object.obj_title ? object.obj_title : object.class.to_s}</span>".html_safe, :url => {:controller => 'profile', 
                  :action => 'track', 
                  :id => object.id,
                  :multi => "yes", 
                  :type => object.class.to_s},
                  :html => { :class => button ? button : "track_small" } %>
    <% else %>
      <%= link_to "<span>Track #{object.obj_title ? object.obj_title : object.class.to_s}</span>".html_safe, {:controller => 'account', :action => 'login'}, :class => button %>
    <% end %>
  <% else %>
    I'm tracking this <%= object.class.to_s %>
  <% end %>
</span>