config/routes.rb
Demo::Application.routes.draw do
 	resource :demo
	resources :categories 
        resource :questions
	resource :answers
	resources :users do 
	  member do
             get :following, :followers
          end
        end
        resources :microposts
        resources :profiles
	resources :sessions
	
    

    
      
 match '/contact', :to => 'pages#contact'
    match '/about',   :to => 'pages#about'
    match '/help',    :to => 'pages#help'
    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'

    match 'sessions/:id/shownewuser',  :to => 'sessions#shownewuser' , :as => :shownewuser
    match 'sessions/:id/signedin',  :to => 'sessions#signedin' , :as => :signedin
    match 'profiles/setuserprofile',  :to => 'profiles#setuserprofile' , :as => :setuserprofile
    match 'sessions/:id/showsurvey', :to => 'sessions#showsurvey', :as => :showsurvey
    match 'sessions/:id/expressyourself', :to => 'sessions#expressyourself', :as => :expressyourself
    match 'sessions/:id/discuss', :to => 'sessions#discuss', :as => :discuss
    match 'sessions/:id/updateanswers', :to => 'sessions#updateanswers', :as => :updateanswers
    match 'sessions/:id/updateProfile', :to => 'sessions#updateProfile', :as => :updateProfile
    
    match '/signout', :to => 'sessions#destroy'
    root :to => 'sessions#signedin'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :id, :name, :pic ,:small_pic, :question_attributes
	has_many :questions, :dependent => :destroy
  validates_presence_of :name,  :id
  accepts_nested_attributes_for :questions
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
layout "frontpage"
respond_to :json
def index
    @categorys = Category.all
  end
  
  def show
   @category = Category.find(params[:data])
   
   @questions = @category.questions.find_all
   
   @current_question_rec =  @questions.first
   @current_question = @current_question_rec.question
   @current_question_id = @current_question_rec.question_id
   @answer =   @answer = Answer.find_by_sql(["SELECT answers.* from answers 
   	   WHERE answers.user_id = ? AND answers.question_id = ?",
   	   (params[:id]), @current_question_id])  
   render
  end
  
  def new
    @category = Category.new
    3.times do
    	    question = @category.questions.build
            4.times { question.answers.build }
    end
  end
  
  def create
    @category = Category.new(params[:Category])
    if @category.save
      flash[:notice] = "Successfully created Category."
      redirect_to @category
    else
      render :action => 'new'
    end
  end
  
  def edit
     @category = Category.find(params[:category])
      if @category.update_attributes (params[:category])
  	 	 
  	 	 
 	  	  flash[:notice] = "Successfully updated Answer."
      redirect_to back
  end
    end
  def update_answers
  	  @category = Category.find(params[:id])
  	  if @category.update_attributes (params[:id])
  	 	 
  	 	 
 	  	  flash[:notice] = "Successfully updated Answer."
      redirect_to back
    end
  end
  
  def update
     @formresults = params[:category]	  
     @category = Category.find(params[:id])	   
     @formresults = params[:category]	  
     @question_id = @formresults[:question_id]
     @user_id = @formresults[:user_id]
     @answer_details = @formresults[:answer]

     @answer=@category.questions.find(@question_id).answers.find_by_user_id(@user_id)
     @answer.agree = @answer_details[:agree]
     @answer.importance = @answer_details[:importance]
     @answer.importance = @answer_details[:comments]
     
     if @answer.save then
     	     @counter = @question_id.to_i
     	     @counter = @counter+1
     	     @current_question_rec = @category.questions.find_by_question_id(@counter)
     	     @current_question = @current_question_rec.question 
     	     @current_question_id = @counter
     	     @answer = @category.questions.find(@current_question_id).answers.find_by_user_id(@user_id)
     	     
     	     
 	 respond_to do |format|
 	     format.html { redirect_to @category }
             format.js { render }
     end 
end
 end
 def updateanswers
     @formresults = params[:category]	  
     @category = Category.find(params[:id])	   
     @formresults = params[:category]	  
     @question_id = @formresults[:question_id]
     @user_id = @formresults[:user_id]
     @answer_details = @formresults[:answer]

     @answer=@category.questions.find(@question_id).answers.find_by_user_id(@user_id)
     @answer.agree = @answer_details[:agree]
     @answer.importance = @answer_details[:importance]
     @answer.importance = @answer_details[:comments]
     
     if @answer.save then
     	     @counter = @question_id.to_i
     	     @counter = @counter+1
     	     @current_question_rec = @category.questions.find_by_question_id(@counter)
     	     @current_question = @current_question_rec.question 
     	     @current_question_id = @counter
     	     @answer = @category.questions.find(@current_question_id).answers.find_by_user_id(@user_id)
     	     
     	     
 	 respond_to do |format|
 	     format.html { redirect_to @category }
             format.js { render }
     end 
end
 end  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Successfully destroyed Category."
    redirect_to Categorys_url
  end
 
end

app/views/categories/_answerrefresh.html.erb
<%= radio_button_tag(:agree , 5) %>
<%= label_tag(:agree_5, "I completely agree ") %>
<%= radio_button_tag(:agree , 4) %>
<%= label_tag(:agree_4, "I agree ") %>
<%= radio_button_tag(:agree , 3) %>
<%= label_tag(:agree_3, "I kind of agree ") %>
<%= radio_button_tag(:agree , 2) %>
<%= label_tag(:agree_2, "I disagree ") %>
<%= radio_button_tag(:agree , 1) %>
<%= label_tag(:agree_1, "I completly disagree ") %>

  This statement is:

<%= radio_button_tag(:importance , 3) %>
<%= label_tag(:importance_3, "Incredibly important ") %>
<%= radio_button_tag(:importance , 2) %>
<%= label_tag(:importance_2, "Kind of important") %>
<%= radio_button_tag(:importance , 3) %>
<%= label_tag(:importance_1, "A good thing to trade for something I care about ") %>

app/views/categories/_commentrefresh.html.erb
<%= text_field_tag :comments %>

app/views/categories/_current_question.html.erb
<%= @current_question %>

app/views/categories/_edit.js.erb
$('#questionarea li').remove();
$('#questionarea li').html('<%= j render(@current_question) %>');
$('#questionarea li').show();

app/views/categories/_form.html.erb
<p>
  <strong>Name:</strong>
  <%=h @category.name %>
</p>

<ol>

<%= form_for( @questions,  :url => updateanswers_path(@questions), :html => { :method =>:put }, :remote => true)  do |f| %>

<ul id='questionarea'>
<%=@current_question %>
</ul>
<div id = 'hidden_field_usr' >
<%=f.hidden_field :user_id, {:value => params[:id]}  %>
</div>
<div id = 'hidden_field_question' >
<%=f.hidden_field :question_id, {:value => @current_question_id} %>
</div>
<%=f.fields_for @answer do |a| %>
         
		<ul id= 'answerarea'>
		<%= a.radio_button(:agree , 5) %>
		<%= a.label(:agree_5, "I completely agree ") %>
		<%= a.radio_button(:agree , 4) %>
		<%= a.label(:agree_4, "I agree ") %>
		<%= a.radio_button(:agree , 3) %>
		<%= a.label(:agree_3, "I kind of agree ") %>
		<%= a.radio_button(:agree , 2) %>
		<%= a.label(:agree_2, "I disagree ") %>
		<%= a.radio_button(:agree , 1) %>
		<%= a.label(:agree_1, "I completly disagree ") %>
	
		  This statement is:
	
		<%= a.radio_button(:importance , 3) %>
		<%= a.label(:importance_3, "Incredibly important ") %>
		<%= a.radio_button(:importance , 2) %>
		<%= a.label(:importance_2, "Kind of important") %>
		<%= a.radio_button(:importance , 3) %>
		<%= a.label(:importance_1, "A good thing to trade for something I care about ") %>
</ul>
<ul>
  <li id ='comments'>Comments:
       <%= a.text_field :comments %>
  </li>
</ul>
	       
<ul>
	<%end %>
	<div id = "qsubmit" > <%= f.submit %> </div>
<%end %>
</ul>
</ol>

app/views/categories/_form.html.erb_experiment1.html.erb
<%= javascript_include_tag 'application', 'form' %>


<p>
  <strong>Name:</strong>
  <%=h @category.name %>
</p>

<ol>

 <% suid = nil %>
<%@id=@category.id %>

<%= form_for @category, remote: true  do |f| %>

<ul id='questionarea'>
<%=@category.surveys.first.question %>
</ul>
<%=hidden_field_tag(:user_id, params[:id]) %>
<%=f.fields_for @category.surveys do |a| %>
         <%= a.hidden_field :survey_id %>
		<ul id= 'answerarea'>
		<%= radio_button_tag(:agree , 5) %>
		<%= label_tag(:agree_5, "I completely agree ") %>
		<%= radio_button_tag(:agree , 4) %>
		<%= label_tag(:agree_4, "I agree ") %>
		<%= radio_button_tag(:agree , 3) %>
		<%= label_tag(:agree_3, "I kind of agree ") %>
		<%= radio_button_tag(:agree , 2) %>
		<%= label_tag(:agree_2, "I disagree ") %>
		<%= radio_button_tag(:agree , 1) %>
		<%= label_tag(:agree_1, "I completly disagree ") %>
	
		  This statement is:
	
		<%= radio_button_tag(:importance , 3) %>
		<%= label_tag(:importance_3, "Incredibly important ") %>
		<%= radio_button_tag(:importance , 2) %>
		<%= label_tag(:importance_2, "Kind of important") %>
		<%= radio_button_tag(:importance , 3) %>
		<%= label_tag(:importance_1, "A good thing to trade for something I care about ") %>
</ul>
<ul>
  <li id ='comments'>Comments:
       <%= text_field_tag :comments %>
  </li>
</ul>
	       
<ul>

	
	<%end %>
	<%= f.submit %>
<%end %>
</ul>
</ol>

app/views/categories/_hiddenparms.html.erb
<%=hidden_field_tag( :question_id, @current_question_id) %>

app/views/categories/_question.html.erb
<%= f.simple_fields_for :invoice_items do |builder| %>
  <%= render 'customer_quote_record', :f => builder %>
<% end %>

app/views/categories/_surveyshow.html.erb
<p>
  <strong>Name:</strong>
  <%=h @category.name %>
</p>

<p>

  <strong>Respond to the statement:</strong>
 </p>
<ol>
<%= javascript_include_tag 'jQuery,application' %>
 <%= javascript_include_tag 'jquery-ui.min' %>
 <%= javascript_include_tag 'onSubmit' %>

<% suid = nil %>
<%@id=@category.id %>
<%z =0 %>
<%= form_for @category , :remote => true, :html => {:method => :put,:onsubmit => 'onSubmit(@id,@answer.survey_id,@answer.user_id ); return false;'}  do |f| %>
<%=f.hidden_field :id %>
  <%= f.fields_for :survey  do |q| %>
        <ul> 
         <%=h @category.surveys[z].question %>
         <% suid =  @category.surveys[z].survey_id %>
         <% z =+1 %>
        <%= f.fields_for :answer do |a| %>
        <%= a.hidden_field :survey_id, value: suid %>
        <%=a.hidden_field :user_id, value: params[:id]%>
        
            <li><%= a.check_box :agree ,value: 5 %>  I completely agree    </li>
	    <li><%= a.check_box :agree ,value: 4 %>  I agree  </li>
	    <li><%= a.check_box :agree ,value: 3 %>  I kind of agree  </li>
	    <li><%= a.check_box :agree ,value: 2 %>  I disagree  </li>
	    <li><%= a.check_box :agree ,value: 1 %>  I completely disagree  </li>
 	<li class="fields">  This statement is:</li>
	    <li><%= a.check_box :importance ,value: 3%>    Incredibly important                            </li>
		<li><%= a.check_box :importance,value: 2 %> Kind of important                               </li>
	       <li><%= a.check_box :importance ,value: 1%> A good thing to trade for something I care about</li>
	       <li>Comments:</li>
	       <li><%= a.text_field :comments %>
          </ul>   
          	 
	<%end%>
	<%= q.button :submit %>
<% end %>
<% end %>
</ol>

app/views/categories/index.html.erb
<div id="content" class="clearfix">
 <%= render :partial => 'layouts/user_nav' %>
 <%= javascript_include_tag 'jquery-1.3.2.min' %>
 <%= javascript_include_tag 'prototype' %>
 <%= javascript_include_tag 'frontpage'%>

  <div class="inner">
    <div class="top_area">          
      <div class="just_for_a_border">
      <div id="nav" >
      <div class="left">
		<div class="right">
	           <ul class="tabs" id="bill_tab_select">
		     <% @header_tabs.each do |tab| 
		        @id = tab[:id]
		        @title = tab[:title] %>
		        <li id='<%= tab[:id] %>/'>
                        <%= link_to "<span>#{tab[:title]}</span>".html_safe , params.merge(:id => tab[:id]) %>
                        </li>
		     <% end %>
 	          </ul>
	       </div>
	</div>
       </div>

       <div id ="questionlist">
       <% @header_tabs.each do |tab| 
		        @id = tab[:id]
		        @style = tab[:style] %> 
       <ul class="medium_question_list" id ="questions_selected" >
         <div id='<%@id%>' style="<% @style %>" >
         <% if @firsttime == "yes" then %>
               <span><span id="popular_ul_title">"Welcome"</span>
         <% else %>      
              <span><span id="popular_ul_title"><%=@title %></span>
              <% select_category(tab , tab[:id])  
                render :partial => 'questions'  
           end %>     
        </span>
        <% end %>
        <% @firsttime = "no" %> 
        </div>
      </div><!-- just for a border -->
     </div><!-- top_area -->	

  <div id="find">
    <p>Where voters and politicians can discuss and learn about the issues for free with no advertising dollars getting in the way <br />Subscribe to RSS feeds to stay in touch with their latest votes. </p>
  </div>

  
  </div><!-- inner -->
</div> <!-- content -->

app/views/categories/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/categories/show.html.erb
<div id="content" class="clearfix">
<%= render :partial => 'layouts/user_profile' %>

          <div class="inner">
          
            <div class="top_area">          
              </div> <!-- top_area -->	             
              <p>Welcome this will be the survey page for user after clicking on a priority icon.</p>
               <div id="middle_area" > 
             <table><tr>
               <div id="middle_area-left" >
               <p>Welcome this will be the survey page for user after clicking on a priority icon.</p>
               </div>
               <div id="middle_area-center" >
               <%= render :partial => 'form' %>
               </div>
               <div id="middle_area-right" >
               <p>Welcome this will be the survey page for user after clicking on a priority icon.</p>
               </div>
               </tr>
               </table>
               </div> <!-- middle_area -->
	  <div id="find">
             <p>Where voters and politicians can discuss and learn about the issues for free with no advertising dollars getting in the way <br />
             Subscribe to RSS feeds to stay in touch with their latest votes. </p>
          </div>
      
    </div>   <!-- inner_area -->
</div>       <!-- content -->

app/views/categories/update.js.erb
$('#questionarea').html( "<%= escape_javascript render :partial => "current_question" %> ");
$('#hiddenparms').html( "<%= escape_javascript render :partial => "hiddenparms" %> ");

app/views/categories/updateanswers.js.erb
$('#questionarea').html( "<%= escape_javascript render :partial => "current_question" %> ");
$('#hiddenparms').html( "<%= escape_javascript render :partial => "hiddenparms" %> ");